export const COMPANY = {
  COMPANY: "COMPANY",
  COMPANY_BTN_EDIT: "COMPANY_BTN_EDIT",
  COMPANY_SETTINGS: "COMPANY_SETTINGS",

  COMPANY_BRANCHES: "COMPANY_BRANCHES",
  COMPANY_BRANCHES_BTN_EDIT: "COMPANY_BRANCHES_BTN_EDIT",

  COMPANY_EMPLOYEES: "COMPANY_EMPLOYEES",
  COMPANY_EMPLOYEES_BTN_EDIT: "COMPANY_EMPLOYEES_BTN_EDIT",
  COMPANY_EMPLOYEES_BTN_ADD: "COMPANY_EMPLOYEES_BTN_ADD",
};

export const SEATING = {
  SEATING: "SEATING",
  SEATING_HALLS: "SEATING_HALLS",

  SEATING_HALLS_TABLE: "SEATING_HALLS_TABLE",

  SEATING_HALLS_TABLE_BTN_TRANSFER: "SEATING_HALLS_TABLE_BTN_TRANSFER",
  SEATING_HALLS_TABLE_BTN_BOOK: "SEATING_HALLS_TABLE_BTN_BOOK",
  SEATING_HALLS_TABLE_BTN_ADD_ORDER: "SEATING_HALLS_TABLE_BTN_ADD_ORDER",
  SEATING_HALLS_TABLE_BTN_NEW_CHECK: "SEATING_HALLS_TABLE_BTN_NEW_CHECK",
  SEATING_HALLS_TABLE_BTN_COMBINE: "SEATING_HALLS_TABLE_BTN_COMBINE",
  SEATING_HALLS_TABLE_BTN_CANCEL: "SEATING_HALLS_TABLE_BTN_CANCEL",
  SEATING_HALLS_TABLE_BTN_CANCEL_STATUS_NEW: "SEATING_HALLS_TABLE_BTN_CANCEL_STATUS_NEW",
  SEATING_HALLS_TABLE_BTN_CANCEL_STATUS_OTHERS: "SEATING_HALLS_TABLE_BTN_CANCEL_STATUS_OTHERS",

  SEATING_HALLS_TABLE_BTN_BLOCK: "SEATING_HALLS_TABLE_BTN_BLOCK",
  SEARING_HALLS_ABLE_BTN_UNBLOCK: "SEARING_HALLS_ABLE_BTN_UNBLOCK",
  SEATING_HALLS_TABLE_BTN_DELETE_ORDER: "SEATING_HALLS_TABLE_BTN_DELETE_ORDER",
  SEATING_HALLS_TABLE_BTN_DELETE_ORDER_STATUS_NEW: "SEATING_HALLS_TABLE_BTN_DELETE_ORDER_STATUS_NEW",
  SEATING_HALLS_TABLE_BTN_DELETE_ORDER_STATUS_OTHERS: "SEATING_HALLS_TABLE_BTN_DELETE_ORDER_STATUS_OTHERS",
  SEATING_HALLS_TABLE_BTN_ADD_CLIENT: "SEATING_HALLS_TABLE_BTN_ADD_CLIENT",

  SEATING_HALLS_TABLE_BTN_RESERVATION_CANCEL: "SEATING_HALLS_TABLE_RESERVATION_CANCEL",
  SEATING_HALLS_TABLE_BTN_RESERVATIONS_LIST: "SEATING_HALLS_TABLE_BTN_RESERVATIONS_LIST",
  SEATING_HALLS_TABLE_RESERVATION_BTN_EDIT: "SEATING_HALLS_TABLE_RESERVATION_BTN_EDIT",
  SEATING_HALLS_TABLE_RESERVATION_BTN_NEW_CHECK: "SEATING_HALLS_TABLE_RESERVATION_BTN_NEW_CHECK",
  SEATING_HALLS_TABLE_RESERVATION_BTN_ACTIVATE: "SEATING_HALLS_TABLE_RESERVATION_BTN_ACTIVATE",
  SEATING_HALLS_TABLE_RESERVATION_BTN_CANCEL: "SEATING_HALLS_TABLE_RESERVATION_BTN_CANCEL",
  SEATING_HALLS_TABLE_RESERVATION_BTN_BLOCK: "SEATING_HALLS_TABLE_RESERVATION_BTN_BLOCK",
  SEATING_HALLS_TABLE_RESERVATION_BTN_TRANSFER: "SEATING_HALLS_TABLE_RESERVATION_BTN_TRANSFER",

  SEATING_RESERVATIONS_LIST: "SEATING_RESERVATIONS_LIST",
  SEATING_STAFF: "SEATING_STAFF",
};

export const KITCHEN = {
  KITCHEN: "KITCHEN",
  KITCHEN_WORKSPACE: "KITCHEN_WORKSPACE",
  KITCHEN_ORDERS_MANAGEMENT: "KITCHEN_ORDERS_MANAGEMENT",

  KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS: "KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS",
  KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_ACCEPT: "KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_ACCEPT",
  KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_READY: "KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_READY",
  KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_RETURN: "KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_RETURN",
  KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_MORE_DETAILS: "KITCHEN_ORDERS_MANAGEMENT_BTN_ORDER_ACTIONS_MORE_DETAILS",

  KITCHEN_CURRENT_STOCK: "KITCHEN_CURRENT_STOCK",
};

export const CATALOG = {
  CATALOG: "CATALOG",

  CATALOG_MENU: "CATALOG_MENU",

  CATALOG_MENU_CATEGORY: "CATALOG_MENU_CATEGORY",
  CATALOG_MENU_BTN_ADD: "CATALOG_MENU_BTN_ADD",
  CATALOG_MENU_BTN_EDIT: "CATALOG_MENU_BTN_EDIT",
  CATALOG_MENU_DELETE_BTN: "CATALOG_MENU_DELETE_BTN",

  CATALOG_MENU_ITEMS: "CATALOG_MENU_ITEMS",
  CATALOG_MENU_ITEMS_BTN_ADD: "CATALOG_MENU_ITEMS_BTN_ADD",
  CATALOG_MENU_ITEMS_BTN_EDIT: "CATALOG_MENU_ITEMS_BTN_EDIT",
  CATALOG_MENU_ITEMS_BTN_DELETE: "CATALOG_MENU_ITEMS_BTN_DELETE",

  CATALOG_FOOD: "CATALOG_FOOD",
  CATALOG_FOOD_BTN_ADD: "CATALOG_FOOD_BTN_ADD",
  CATALOG_FOOD_BTN_EDIT: "CATALOG_FOOD_BTN_EDIT",
  CATALOG_FOOD_BTN_DELETE: "CATALOG_FOOD_BTN_DELETE",

  CATALOG_PRODUCTS: "CATALOG_PRODUCTS",
  CATALOG_PRODUCT_BTN_ADD: "CATALOG_PRODUCT_BTN_ADD",
  CATALOG_PRODUCT_BTN_EDIT: "CATALOG_PRODUCT_BTN_EDIT",
  CATALOG_PRODUCT_BTN_DELETE: "CATALOG_PRODUCT_BTN_DELETE",

  CATALOG_INGREDIENTS: "CATALOG_INGREDIENTS",
  CATALOG_INGREDIENT_BTN_ADD: "CATALOG_INGREDIENT_BTN_ADD",
  CATALOG_INGREDIENT_BTN_EDIT: "CATALOG_INGREDIENT_BTN_EDIT",
  CATALOG_INGREDIENT_BTN_DELETE: "CATALOG_INGREDIENT_BTN_DELETE",

  CATALOG_SEMI_FINISHED: "CATALOG_SEMI_FINISHED",
  CATALOG_SEMI_FINISHED_BTN_ADD: "CATALOG_SEMI_FINISHED_BTN_ADD",
  CATALOG_SEMI_FINISHED_BTN_EDIT: "CATALOG_SEMI_FINISHED_BTN_EDIT",
  CATALOG_SEMI_FINISHED_BTN_DELETE: "CATALOG_SEMI_FINISHED_BTN_DELETE",

  CATALOG_CATERING_SERVICE: "CATALOG_CATERING_SERVICE",
  CATALOG_CATERING_SERVICE_BTN_ADD: "CATALOG_CATERING_SERVICE_BTN_ADD",
  CATALOG_CATERING_SERVICE_BTN_EDIT: "CATALOG_CATERING_SERVICE_BTN_EDIT",
  CATALOG_CATERING_SERVICE_BTN_DELETE: "CATALOG_CATERING_SERVICE_BTN_DELETE",

  CATALOG_BAR: "CATALOG_BAR",
  CATALOG_BAR_BTN_ADD: "CATALOG_BAR_BTN_ADD",
  CATALOG_BAR_BTN_EDIT: "CATALOG_BAR_BTN_EDIT",
  CATALOG_BAR_BTN_DELETE: "CATALOG_BAR_BTN_DELETE",
};

export const MANAGEMENT = {
  MANAGEMENT: "MANAGEMENT",
  MANAGEMENT_DEPARTMENTS: "MANAGEMENT_DEPARTMENTS",
  MANAGEMENT_DEPARTMENTS_BTN_ADD: "MANAGEMENT_DEPARTMENTS_BTN_ADD",
  MANAGEMENT_DEPARTMENTS_BTN_EDIT: "MANAGEMENT_DEPARTMENTS_BTN_EDIT",

  MANAGEMENT_HALLS_SETTINGS: "MANAGEMENT_HALLS_SETTINGS",
  MANAGEMENT_HALLS_SETTINGS_BTN_ADD: "MANAGEMENT_HALLS_SETTINGS_BTN_ADD",
  MANAGEMENT_HALLS_SETTINGS_BTN_EDIT: "MANAGEMENT_HALLS_SETTINGS_BTN_EDIT",
  MANAGEMENT_HALLS_SETTINGS_BTN_ADD_TABLES: "MANAGEMENT_HALLS_SETTINGS_BTN_ADD_TABLES",
  MANAGEMENT_HALLS_SETTINGS_BTN_EDIT_TABLES: "MANAGEMENT_HALLS_SETTINGS_BTN_EDIT_TABLES",
  MANAGEMENT_HALLS_SETTINGS_TABLES_LIST_VIEW: "MANAGEMENT_HALLS_SETTINGS_TABLES_LIST_VIEW",

  MANAGEMENT_CABINET_SERVICE_FEE_PERCENT: "MANAGEMENT_CABINET_SERVICE_FEE_PERCENT",
  MANAGEMENT_CABINET_SERVICE_FEE_PERCENT_BTN_EDIT: "MANAGEMENT_CABINET_SERVICE_FEE_PERCENT_BTN_EDIT",
};

export const REPORTS = {
  REPORTS: "REPORTS",
  REPORTS_RECEIPTS: "REPORTS_RECEIPTS",
  REPORTS_ORDERS: "REPORTS_ORDERS",
};

export const WAREHOUSE = {
  WAREHOUSE: "WAREHOUSE",
  WAREHOUSE_SUPPLIERS: "WAREHOUSE_SUPPLIERS",

  WAREHOUSE_STOCK_IN: "WAREHOUSE_STOCK_IN",
  WAREHOUSE_STOCK_IN_ADD: "WAREHOUSE_STOCK_IN_ADD",
  WAREHOUSE_STOCK_IN_ADD_DETAILS: "WAREHOUSE_STOCK_IN_ADD_DETAILS",
  WAREHOUSE_STOCK_IN_DETAILS: "WAREHOUSE_STOCK_IN_DETAILS",

  WAREHOUSE_STOCK_OUT: "WAREHOUSE_STOCK_OUT",
  WAREHOUSE_STOCK_OUT_DETAILS: "WAREHOUSE_STOCK_OUT_DETAILS",
  WAREHOUSE_STOCK_OUT_ADD: "WAREHOUSE_STOCK_OUT_ADD",
  WAREHOUSE_STOCK_OUT_ADD_DETAILS: "WAREHOUSE_STOCK_OUT_ADD_DETAILS",
};

export const CUSTOMER_BASE = {
  CUSTOMER_BASE: "CUSTOMER_BASE",
  CUSTOMER_BASE_LIST: "CUSTOMER_BASE_LIST",
  CUSTOMER_BASE_LIST_BTN_ADD: "CUSTOMER_BASE_LIST_BTN_ADD",
  CUSTOMER_BASE_LIST_BTN_EDIT: "CUSTOMER_BASE_LIST_BTN_EDIT",

  CUSTOMER_BASE_CUSTOMERS: "CUSTOMER_BASE_CUSTOMERS",
};

export const SETTINGS = {
  SETTINGS: "SETTINGS",
  SETTINGS_PROFILE: "SETTINGS_PROFILE",
  SETTINGS_SECURITY: "SETTINGS_SECURITY",
  SETTINGS_SECURITY_CHANGE_PASSWORD: "SETTINGS_SECURITY_CHANGE_PASSWORD",
};

export const cabinet = {
  ...COMPANY,
  ...SEATING,
  ...KITCHEN,
  ...CATALOG,
  ...MANAGEMENT,
  ...REPORTS,
  ...CUSTOMER_BASE,
  ...SETTINGS,
  ...WAREHOUSE,
};
