export const testMenuData = [
  {
    id: 320763657,
    name: "HuKKa категория",
    parentId: null,
    parentName: null,
    enabled: true,
    productCount: 0,
    salesStats: null,
    children: [],
    branchId: null,
    categoryNameUz: null,
    descriptionRu: null,
    descriptionUz: null,
    imageUrl: null,
    deleted: null,
    file: null,
    templateId: null,
    templateName: null,
    updateImage: false,
    categoryStatus: null,
    agreementId: null,
  },
  {
    id: 320763889,
    name: "Mutorjon",
    parentId: null,
    parentName: null,
    enabled: true,
    productCount: 0,
    salesStats: null,
    children: [],
    branchId: null,
    categoryNameUz: null,
    descriptionRu: null,
    descriptionUz: null,
    imageUrl: null,
    deleted: null,
    file: null,
    templateId: null,
    templateName: null,
    updateImage: false,
    categoryStatus: null,
    agreementId: null,
  },
  {
    id: -148,
    name: "Алкоголь",
    parentId: null,
    parentName: null,
    enabled: true,
    productCount: 1215,
    salesStats: null,
    children: [
      {
        id: -525,
        name: "Вермут",
        parentId: -148,
        parentName: null,
        enabled: true,
        productCount: 0,
        salesStats: null,
        children: [],
        branchId: null,
        categoryNameUz: null,
        descriptionRu: null,
        descriptionUz: null,
        imageUrl: null,
        deleted: null,
        file: null,
        templateId: null,
        templateName: null,
        updateImage: false,
        categoryStatus: null,
        agreementId: null,
      },
      {
        id: -176,
        name: "Вино",
        parentId: -148,
        parentName: null,
        enabled: true,
        productCount: 0,
        salesStats: null,
        children: [
          {
            id: -279,
            name: "Игристые вина",
            parentId: -176,
            parentName: null,
            enabled: true,
            productCount: 0,
            salesStats: null,
            children: [],
            branchId: null,
            categoryNameUz: null,
            descriptionRu: null,
            descriptionUz: null,
            imageUrl: null,
            deleted: null,
            file: null,
            templateId: null,
            templateName: null,
            updateImage: false,
            categoryStatus: null,
            agreementId: null,
          },
        ],
      },
    ],
  },
];
