export const MONITORING = {
  MONITORING: "MONITORING",
  MONITORING_COMPANIES: "MONITORING_COMPANIES",
  MONITORING_LOGS: "MONITORING_LOGS",
};

export const MANAGEMENT = {
  MANAGEMENT: "MANAGEMENT",
  MANAGEMENT_USERS: "MANAGEMENT_USERS",
  MANAGEMENT_SYSTEM_UPGRADE: "MANAGEMENT_SYSTEM_UPGRADE",
};

export const admin = {
  ...MONITORING,
  ...MANAGEMENT,
};
